/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as InstructorRouteImport } from './routes/instructor'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesArmCortexM4Stm32f407RouteImport } from './routes/courses.arm-cortex-m4-stm32f407'
import { Route as CoursesMicrocontrollerCProgrammingRouteImport } from './routes/courses.microcontroller-c-programming'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesArmCortexM4Stm32f407Route =
  CoursesArmCortexM4Stm32f407RouteImport.update({
    id: '/courses/arm-cortex-m4-stm32f407',
    path: '/courses/arm-cortex-m4-stm32f407',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesMicrocontrollerCProgrammingRoute =
  CoursesMicrocontrollerCProgrammingRouteImport.update({
    id: '/courses/microcontroller-c-programming',
    path: '/courses/microcontroller-c-programming',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/instructor': typeof InstructorRoute
  '/courses/arm-cortex-m4-stm32f407': typeof CoursesArmCortexM4Stm32f407Route
  '/courses/microcontroller-c-programming': typeof CoursesMicrocontrollerCProgrammingRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/instructor': typeof InstructorRoute
  '/courses/arm-cortex-m4-stm32f407': typeof CoursesArmCortexM4Stm32f407Route
  '/courses/microcontroller-c-programming': typeof CoursesMicrocontrollerCProgrammingRoute
  '/courses': typeof CoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/instructor': typeof InstructorRoute
  '/courses/arm-cortex-m4-stm32f407': typeof CoursesArmCortexM4Stm32f407Route
  '/courses/microcontroller-c-programming': typeof CoursesMicrocontrollerCProgrammingRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/instructor'
    | '/courses/arm-cortex-m4-stm32f407'
    | '/courses/microcontroller-c-programming'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/instructor'
    | '/courses/arm-cortex-m4-stm32f407'
    | '/courses/microcontroller-c-programming'
    | '/courses'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/instructor'
    | '/courses/arm-cortex-m4-stm32f407'
    | '/courses/microcontroller-c-programming'
    | '/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  InstructorRoute: typeof InstructorRoute
  CoursesArmCortexM4Stm32f407Route: typeof CoursesArmCortexM4Stm32f407Route
  CoursesMicrocontrollerCProgrammingRoute: typeof CoursesMicrocontrollerCProgrammingRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/arm-cortex-m4-stm32f407': {
      id: '/courses/arm-cortex-m4-stm32f407'
      path: '/courses/arm-cortex-m4-stm32f407'
      fullPath: '/courses/arm-cortex-m4-stm32f407'
      preLoaderRoute: typeof CoursesArmCortexM4Stm32f407RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/microcontroller-c-programming': {
      id: '/courses/microcontroller-c-programming'
      path: '/courses/microcontroller-c-programming'
      fullPath: '/courses/microcontroller-c-programming'
      preLoaderRoute: typeof CoursesMicrocontrollerCProgrammingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  InstructorRoute: InstructorRoute,
  CoursesArmCortexM4Stm32f407Route: CoursesArmCortexM4Stm32f407Route,
  CoursesMicrocontrollerCProgrammingRoute:
    CoursesMicrocontrollerCProgrammingRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
